language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- make devenv
script: make check
deploy:
  provider: pypi
  user: fridex
  password:
    secure: YMsU6rXjfmBLb7rUCP/x4+eYJ+ngmwgFy806O50eiNMk9OQaQlk0EEghnOxwo/nRDElnSXgXZa2zRGEwY/aBDTs4S2akrmI0nLoi0wS/jmCtj4sO4xqYLw6JGTzqJb4qoDqebjCMdivgL1NEQJgiHKAZQrihWpjSomSyzKsLkH4iTGzLZRM514zOoPQISzurSFpDhK1IUDhPLkfcAsUcMzRQkRLiwwYiYUITfl2cBH90M8xnEE9JYWWoEDcp/oQ9AnwqGDOF0Z0V1C/aX6oZz4RYOB+cW7wtDLwZTCJD9ws3xBLw+GpA5v4fhMRWt2SXlKTCOCty9vSmR/MlxI8m+YtlJNW0yQPCOS0PMlKtOaZ2ebym6pB0fX4Bx/peKNZKeQqjcH/fPd/11TzVFgIhz+30wtoEK+c8d0z6rVLdEbjyQRGj4up6cdzwWtlK6vur+21s2mZRapTz6DZXddF4X7AR2BrtrHjMkzrXelAj4RVBVNRkuYo+JbrWibJvjEFwQIEy0HOA3x9tEehZ/Fb+cntfqD0WlybLN39j3ti0IMeeP4p8Yg6nUdgzya2lLvInbirRY9SypfmLRo+Md8GkFW9twwRDoZIjGYmQohBf0eT0dpXMBRO2NnKJuawDyUsk8KBaoLGM2bk1jzjaSee/+rnA7/zO4ZAlEstJmF5QdlI=
  on:
    tags: true
    branch: master
  distributions: sdist bdist_wheel
